### ISSUE TITLE
Diffutils with load more

### ISSUE THREAD

**Issue by urvish91** [manneohlund/smart-recycler-adapter#11]
While using diffutils with load more then it is crashing and saying inconsistency detect. Indexoutofbound exception.

**Comment by manneohlund** [comment]
Thanks for reporting and it sounds like a bug! 
Do you have an code snippet to share for more context?

**Comment by urvish91** [comment]
Hi Actually I don't have code snippet, As I have done modification later on in your code and then use it. there is so many problems I am facing while using load more. You may try to set load more enabled true and then set your data using diffutils. 

Also you there is a bug like if I want to turn of the pagination once I reach to end of all pages then when user swipe refresh with first page API call then my pagination should again be enabled but it is not working.

Also another bug is that when user set custom load more resource layout then it is crashing if they don't put button. so actually there are so many issues which I was facing in load more integration. but I used your library as module, and done modification and everything works fine. but not diffUtils related issue.

So I dropped plan to use this unless it is not stable.

Hope to have fix soon regarding all above issues, so that we can use your library as it is. and thank you very much for preparing such awesome library which reduced so much boilerplate code.

**Comment by manneohlund** [comment]
@urvish91 Thanks for reporting these important issues, really helpful! 
I've created some bug and improvement tickets and will try to fix them asap! 
Will get back and refer to this issue in coming PRs :)
Thanks for finding this library useful and don't hesitate to report bugs or request features! 🎖

**Comment by manneohlund** [comment]
@urvish91 Thanks for your patience! This issue is adressed in #14 
Do not hesitate to report new bugs, improvements, feature requests!
