### ISSUE TITLE
Does the library has sticky headers?

### ISSUE THREAD

**Issue by jrcacd** [manneohlund/smart-recycler-adapter#12]

**Comment by manneohlund** [comment]
Hi @jrcacd, Not at the moment, but i have it in the backlog for upcoming releases. 
I'll notify you when it's available.

**Comment by manneohlund** [comment]
@jrcacd Sorry for the delay (been really busy with work n stuff) but now sticky header is supported for regular vertical linear recycler view with `io.github.manneohlund:smart-recycler-adapter-stickyheader:1.0.0-alpha01` extension library 🚀
