### ISSUE TITLE
Does this Library support Adapter Item Filter?

### ISSUE THREAD

**Issue by HenryChigbo** [manneohlund/smart-recycler-adapter#13]
If not what is the best way to implement it?

**Comment by manneohlund** [comment]
Hi @HenryChigbo! 
No not at the moment.
The issue with item filtering is that it preferably should be done asynchronously and thus threading is required. I'm working on implementing Kotlin coroutines for filtering items.
I'll notify when it's available, stay tuned :)

**Comment by manneohlund** [comment]
To answer your question, try look into [coroutines](https://kotlinlang.org/docs/reference/coroutines/coroutines-guide.html) for seamless threading in Kotlin.

**Comment by HenryChigbo** [comment]
It is an old code base in Java not Kotlin
