### ISSUE TITLE
Can't resolve smart-recycler-adapter-nestedadapter:1.0.0-alpha01

### ISSUE THREAD

**Issue by dacre-denny** [manneohlund/smart-recycler-adapter#31]
Getting error:
**Failed to resolve: io.github.manneohlund:smart-recycler-adapter-nestedadapter:1.0.0-alpha01**

When including:
**implementation 'io.github.manneohlund:smart-recycler-adapter-nestedadapter:1.0.0-alpha01'**

**Comment by manneohlund** [comment]
Hmm I will check jcenter linking. 
In the meantime add:
`maven { url "https://dl.bintray.com/manneohlund/maven" }` under repositories in your gradle file.
Thanks for reporting and stay tuned 🖖

**Comment by manneohlund** [comment]
Now it should work with jcenter 🚀

**Comment by dacre-denny** [comment]
All resolved - thank you :+1:
