### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by perusudroid** [manneohlund/smart-recycler-adapter#5]
Does this library support pagination? I did'nt find any documentation for it. Pls add it too...

**Comment by manneohlund** [comment]
No it does not support pagination atm. But it shouldn't be hard to implement in the lib and I'm considering adding it in near future. So hang in there and I'll keep you posted!

**Comment by manneohlund** [comment]
@perusudroid Added in #6. Happy testing and tell me what you think!
